services:
  postgres:
    container_name: 'postgres-container-desaf-back'
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=magalubd'
      - 'POSTGRES_PASSWORD=123'
      - 'POSTGRES_USER=admin'
    ports:
      - '5432:5432'

  desafio-magalu:
    container_name: 'desafio-magalu-container'
    image: 'desafio-magalu:latest'
    build: .
    ports:
      - '8080:8080'
    depends_on:
      - postgres
    environment:
      - 'DATABASE_URL=postgres://admin:123@postgres:5432/magalubd'