services:
  postgres:
    container_name: 'postgres-container-desaf-back'
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=magalubd'
      - 'POSTGRES_PASSWORD=123'
      - 'POSTGRES_USER=admin'
    ports:
      - '5432:5432'
